[project]
name = "bookmark-cluster"
version = "0.1.0"
description = "Spectral clustering for bookmarks"
requires-python = ">=3.12"
dependencies = [
    # url fetching encounters ocassional website roadblocks
    "selenium",
    "selenium-stealth",
]
